DEVO-504: Update circle image.
tulibraries/tul_cob-web-solr pull request #27
Opened 2021-12-02 19:02 UTC by dkinzer

2021-12-02 19:13 UTC, sensei100 requested changes
The circleci images are being deprecated.  We need to use cimg.

2021-12-02 19:13 UTC, sensei100 commented on .circleci/config.yml
> +      - image: circleci/python:3.7.11
```suggestion
      - image: cimg/python:3.7.11
```

2021-12-02 22:03 UTC, dkinzer commented on .circleci/config.yml
> +      - image: circleci/python:3.7.11
🤦🏽

2021-12-03 14:06 UTC, sensei100 approved these changes

2021-12-03 14:06 UTC, merged